name = "ams"
main = "src/server/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ams-db"
database_id = "ams-dev-db-id"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "ams-dev-kv-id"

[vars]
ENVIRONMENT = "development"
QR_ACTIVE_KID = "k1"
# 32-byte base64 random dev key for AES-256-GCM JWE
QR_KEY_K1 = "Cs0Ugc8R/Z7QAprW1w5jqKyh8/Wlw46XPjN2W5GeAKU="
SESSION_SECRET = "ams-dev-session-secret-key-32-chars-long"
APP_ISSUER = "https://absen.local"
APP_AUDIENCE = "ams"
