export const ErrorCode = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',

  // QR / Token Errors
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_ACTIVE_YET: 'TOKEN_NOT_ACTIVE_YET',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  UNKNOWN_KEY: 'UNKNOWN_KEY',
  WRONG_AUDIENCE: 'WRONG_AUDIENCE',
  WRONG_ISSUER: 'WRONG_ISSUER',
  WRONG_EVENT: 'WRONG_EVENT',
  UNIVERSAL_NOT_ALLOWED: 'UNIVERSAL_NOT_ALLOWED',
  MAX_USES_EXCEEDED: 'MAX_USES_EXCEEDED',

  // Member Errors
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_INACTIVE: 'MEMBER_INACTIVE',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  EXTERNAL_ID_TAKEN: 'EXTERNAL_ID_TAKEN',

  // Event Errors
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_INACTIVE: 'EVENT_INACTIVE',
  EVENT_CLOSED: 'EVENT_CLOSED',
  EVENT_NOT_STARTED: 'EVENT_NOT_STARTED',
  EVENT_ENDED: 'EVENT_ENDED',

  // Attendance Errors
  ALREADY_SCANNED: 'ALREADY_SCANNED',
  ATTENDANCE_FAILED: 'ATTENDANCE_FAILED',

  // Validation / General Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
